apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-cronjob
  namespace: kube-system
data:
  ETCDCTL_API: "3"
  ETCD_ENDPOINT: https://127.0.0.1:2379
  ETCD_CACERT_PATH: /etc/kubernetes/pki/etcd/ca.crt
  ETCD_KEY_PATH: /etc/kubernetes/pki/apiserver-etcd-client.key
  ETCD_CERT_PATH: /etc/kubernetes/pki/apiserver-etcd-client.crt
  SNAPSHOT_PATH: /tmp/etcd-snapshots
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-snapshots
  labels: #Labels 
    app: etcd-backup
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.205
    path: "/mnt/nfs_shares/etcd-snapshots"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-snapshots-pvc
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: etcd-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Mi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup-cronjob
  namespace: kube-system
spec: # CronJobSpec
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate: #JobTemplateSpec
    spec: # JobSpec
      backoffLimit: 2
      parallelism: 1
      template: # PodTemplateSpec
        metadata:
          labels:
            app: etcd-backup-cronjob
        spec:
          restartPolicy: Never
          hostNetwork: true
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      component: etcd
                  namespaces:
                    - kube-system
                  topologyKey: "kubernetes.io/hostname"
          containers:
            - name: etcdctl
              image: anonoz/etcdctl-arm64:3.4.13
              command:
                - /bin/sh
              args:
                - -c
                - "cd ${SNAPSHOT_PATH}; ls -t | grep ^snapshotdb | tail -n +11 | xargs rm ||:; etcdctl --endpoints=${ETCD_ENDPOINT} --key=${ETCD_KEY_PATH} --cert=${ETCD_CERT_PATH} --cacert=${ETCD_CACERT_PATH} snapshot save ${SNAPSHOT_PATH}/snapshotdb-$(date -u +%Y%m%d-%H%M)"
              envFrom:
                - configMapRef:
                    name: etcd-backup-cronjob
              volumeMounts:
                - name: etcd-certs
                  mountPath: /etc/kubernetes/pki
                - name: etcd-snapshots
                  mountPath: /tmp/etcd-snapshots
          volumes:
            - name: etcd-certs
              hostPath:
                path: /etc/kubernetes/pki
            - name: etcd-snapshots
              persistentVolumeClaim:
                claimName: etcd-snapshots-pvc
          tolerations:
            - key: "node.kubernetes.io/unschedulable"
              operator: "Exists"
              effect: "NoSchedule"
