apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fyp-ingress
spec:
  rules:
  - host: fyp.anonoz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fyp-webapp
            port:
              number: 3000
  tls:
  - hosts:
    - fyp.anonoz.com
    secretName: fyp-cloudflare-tls
