apiVersion: v1
kind: ServiceAccount
metadata:
  name: anonoz-macbookair
  namespace: fyp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anonoz-macbookair-fyp-access
  namespace: fyp
rules:
  - apiGroups: ["", "apps", "batch", "networking", "storage", "autoscaling", "extensions"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anonoz-macbookair-fyp-access
  namespace: fyp
subjects:
  - kind: ServiceAccount
    name: anonoz-macbookair
    namespace: fyp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anonoz-macbookair-fyp-access
