apiVersion: v1
kind: ConfigMap
metadata:
  name: fyp-sidekiq-rails-configmap
data:
  RAILS_ENV: production
  SECRET_KEY_BASE: abc1234
  DATABASE_URL: postgres://user:pass@fyp-psql-nodeport:5432/db
  REDIS_URL: redis://fyp-redis-actioncable:6379/1
  FFNN_URL: http://fyp-dbow-classifier:6002
  RF_URL: http://fyp-dbow-classifier:6002
  SVM_URL: http://fyp-dbow-classifier:6002
  LSTM_URL: http://fyp-skipgram-classifier:6001
  HANZO_URL: http://fyp-skipgram-classifier:6001
  GRU_URL: http://fyp-skipgram-classifier:6001
  GENJI_URL: http://fyp-skipgram-classifier:6001
  RAILS_SERVE_STATIC_FILES: "true"
  RAILS_LOG_TO_STDOUT: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-sidekiq
  labels:
    app: fyp-sidekiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fyp-sidekiq
  template:
    metadata:
      labels:
        app: fyp-sidekiq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values:
                    - "arm64"
      containers:
        - name: sidekiq
          image: anonoz/fyp-webapp-arm64:8729331b653fb0577602afa8b2550544ca7ad9cd
          imagePullPolicy: "IfNotPresent"
          command:
            - bundle
            - exec
            - sidekiq
          envFrom:
            - configMapRef:
                name: fyp-sidekiq-rails-configmap
